export {
  getE1PriNumManipulateRowBg as getE1PriPSTNCallInOriCalleeIDRowBg,
  e1PriNumManipulateEditIconStyle as e1PriPSTNCallInOriCalleeIDEditIconStyle,
  handleE1PriNumManipulateEditIconHover as handleE1PriPSTNCallInOriCalleeIDEditIconHover,
  e1PriNumManipulateFixedAlertSx as e1PriPSTNCallInOriCalleeIDFixedAlertSx,
  e1PriNumManipulatePageWrapStyle as e1PriPSTNCallInOriCalleeIDPageWrapStyle,
  e1PriNumManipulatePageInnerStyle as e1PriPSTNCallInOriCalleeIDPageInnerStyle,
  e1PriNumManipulateSelectedBadgeStyle as e1PriPSTNCallInOriCalleeIDSelectedBadgeStyle,
  e1PriNumManipulateLoadingWrapStyle as e1PriPSTNCallInOriCalleeIDLoadingWrapStyle,
  e1PriNumManipulateEmptyWrapStyle as e1PriPSTNCallInOriCalleeIDEmptyWrapStyle,
  e1PriNumManipulateEmptyTitleStyle as e1PriPSTNCallInOriCalleeIDEmptyTitleStyle,
  e1PriNumManipulateTableScrollStyle as e1PriPSTNCallInOriCalleeIDTableScrollStyle,
  E1_PRI_NUM_MANIPULATE_CARD_RADIUS as E1PRIPSTNCALLINORICALLEEID_CARD_RADIUS,
} from "./E1PriNumManipulateSharedTableHelpers";
