import {
  EXTENSION_TABLE_CARD_RADIUS as CARD_RADIUS,
  extensionPageWrapStyle as sipAccessControlPageWrapStyle,
  extensionPageInnerStyle as sipAccessControlPageInnerStyle,
  extensionCardStyle as sipAccessControlCardStyle,
  extensionToolbarStyle as sipAccessControlToolbarStyle,
  extensionFixedAlertSx as sipAccessControlFixedAlertSx,
  extensionCancelBtnStyle as sipAccessControlCancelBtnStyle,
  extensionPrimaryBtnStyle as sipAccessControlPrimaryBtnStyle,
  addNewModalFooterBtnStyle,
  extensionSelectedBadgeStyle as sipAccessControlSelectedBadgeStyle,
  extensionModalCancelBtnStyle as sipAccessControlModalCancelBtnStyle,
  extensionPaginationStyle as sipAccessControlPaginationStyle,
  tdStyle,
  getExtensionTdStyle as getSipAccessControlTdStyle,
  getExtensionRowBg as getSipAccessControlRowBg,
  extensionTableCheckboxSx as sipAccessControlCheckboxSx,
  TH,
} from "../../../../components/common";

export const FIELD_RADIUS = 4;

export {
  CARD_RADIUS,
  sipAccessControlPageWrapStyle,
  sipAccessControlPageInnerStyle,
  sipAccessControlCardStyle,
  sipAccessControlToolbarStyle,
  sipAccessControlFixedAlertSx,
  sipAccessControlCancelBtnStyle,
  sipAccessControlPrimaryBtnStyle,
  addNewModalFooterBtnStyle,
  sipAccessControlSelectedBadgeStyle,
  sipAccessControlModalCancelBtnStyle,
  sipAccessControlPaginationStyle,
  tdStyle,
  getSipAccessControlTdStyle,
  getSipAccessControlRowBg,
  sipAccessControlCheckboxSx,
  TH,
};
