// Port FXS Page Constants

// Table columns
export const PORT_FXS_TABLE_COLUMNS = [
  { key: 'modify', label: 'Modify', width: '60px' },
  { key: 'port', label: 'Port', width: '60px' },
  { key: 'type', label: 'Type', width: '80px' },
  { key: 'sipAccount', label: 'SIP Account', width: '120px' },
  { key: 'displayName', label: 'Display Name', width: '120px' },
  { key: 'autoDialNum', label: 'Auto Dial Num', width: '120px' },
  { key: 'dnd', label: 'DND', width: '80px' },
  { key: 'forward', label: 'Forward', width: '80px' },
  { key: 'fwdType', label: 'FWD Type', width: '100px' },
  { key: 'fwdNumber', label: 'FWD Number', width: '120px' },
  { key: 'cid', label: 'CID', width: '80px' },
  { key: 'callWaiting', label: 'Call Waiting', width: '100px' },
  { key: 'regStatus', label: 'Reg Status', width: '100px' },
  { key: 'echoCanceller', label: 'Echo Canceller', width: '120px' },
  { key: 'colorRing', label: 'Color Ring', width: '100px' },
  { key: 'colorRingIndex', label: 'Color Ring Index', width: '120px' },
  { key: 'inputGain', label: 'Input Gain', width: '100px' },
  { key: 'outputGain', label: 'Output Gain', width: '100px' },
];

// Items per page
export const PORT_FXS_ITEMS_PER_PAGE = 16;

// Total ports
export const PORT_FXS_TOTAL_PORTS = 32;

// Initial port data structure
export const PORT_FXS_INITIAL_DATA = {
  port: 1,
  type: 'FXS',
  sipAccount: '---',
  displayName: '---',
  autoDialNum: '---',
  dnd: 'Disable',
  forward: 'Disable',
  fwdType: '---',
  fwdNumber: '---',
  cid: 'Enable',
  callWaiting: 'Disable',
  regStatus: 'Unregistered',
  echoCanceller: 'Enable',
  colorRing: 'Disable',
  colorRingIndex: '---',
  inputGain: 0,
  outputGain: 0,
};

// Batch Modify Form Fields
export const PORT_FXS_BATCH_MODIFY_FIELDS = [
  // Reordered and adjusted to match reference HTML layout and behavior
  {
    key: 'startingPort',
    label: 'Starting Port',
    type: 'select',
    options: Array.from({ length: PORT_FXS_TOTAL_PORTS }, (_, i) => String(i + 1)),
    default: '1',
  },
  {
    key: 'endingPort',
    label: 'Ending Port',
    type: 'select',
    options: Array.from({ length: PORT_FXS_TOTAL_PORTS }, (_, i) => String(i + 1)),
    default: '1',
  },
  {
    key: 'batchRegister',
    label: 'Batch Register',
    type: 'checkbox',
    default: true,
  },
  {
    key: 'registerPort',
    label: 'Register Port',
    type: 'select',
    options: ['No', 'Yes'],
    default: 'No',
    conditional: 'batchRegister',
  },
  {
    key: 'batchAccount',
    label: 'Batch Account',
    type: 'checkbox',
    default: true,
  },
  {
    key: 'startingSipAccount',
    label: 'Starting SIP Account',
    type: 'text',
    default: '',
    conditional: 'batchAccount',
  },
  {
    key: 'startingDisplayName',
    label: 'Starting Display Name',
    type: 'text',
    default: '',
    conditional: 'batchAccount',
  },
  {
    key: 'startingAuthPassword',
    label: 'Starting Authentication Password',
    type: 'password',
    default: '',
    conditional: 'batchAccount',
    conditionalParent: 'registerPort',
    conditionalParentValue: 'Yes',
  },
  {
    key: 'displayNamePreferred',
    label: 'Display Name Preferred',
    type: 'checkbox',
    default: false,
    conditional: 'batchAccount',
  },
  {
    key: 'sipAccountBatchRule',
    label: 'SIP Account Batch Rule',
    type: 'select',
    options: ['Increase', 'Decrease'],
    default: 'Increase',
    conditional: 'batchAccount',
  },
  {
    key: 'sipAccountBatchStepSize',
    label: 'SIP Account Batch Step Size',
    type: 'text',
    default: '1',
    validation: 'integer',
    conditional: 'batchAccount',
  },
  {
    key: 'displayNameBatchRule',
    label: 'Display Name Batch Rule',
    type: 'select',
    options: ['Increase', 'Decrease', 'All Same'],
    default: 'All Same',
    conditional: 'batchAccount',
  },
  {
    key: 'displayNameBatchStepSize',
    label: 'Display Name Batch Step Size',
    type: 'text',
    default: '1',
    validation: 'integer',
    conditional: 'batchAccount',
    conditionalParent: 'displayNameBatchRule',
    conditionalParentValue: ['Increase', 'Decrease'],
  },
  {
    key: 'authPasswordBatchRule',
    label: 'Authentication Password Batch Rule',
    type: 'select',
    options: ['Increase', 'Decrease', 'All Same'],
    default: 'All Same',
    conditional: 'batchAccount',
    conditionalParent: 'registerPort',
    conditionalParentValue: 'Yes',
  },
  {
    key: 'authPasswordBatchStepSize',
    label: 'Authentication Password Batch Step Size',
    type: 'text',
    default: '1',
    validation: 'integer',
    conditional: 'batchAccount',
    conditionalParent: 'registerPort',
    conditionalParentValue: 'Yes',
  },
  // Removed authentication username & password step/username rules per request
  {
    key: 'batchConfigure',
    label: 'Batch Configure',
    type: 'checkbox',
    default: true,
  },
  {
    key: 'autoDialNumberEnable',
    label: 'Auto Dial Number',
    type: 'checkbox',
    default: false,
    conditional: 'batchConfigure',
  },
  {
    key: 'autoDialNumber',
    label: 'Auto Dial Number',
    type: 'text',
    default: '',
    conditional: 'batchConfigure',
    conditionalParent: 'autoDialNumberEnable',
  },
  {
    key: 'waitTimeBeforeAutoDial',
    label: 'Wait Time before Auto Dial (s)',
    type: 'text',
    default: '0',
    validation: 'integer',
    conditional: 'batchConfigure',
    conditionalParent: 'autoDialNumberEnable',
  },
  {
    key: 'inputGain',
    label: 'Input Gain (dB)',
    type: 'text',
    default: '0',
    validation: 'integer',
    conditional: 'batchConfigure',
  },
  {
    key: 'outputGain',
    label: 'Output Gain (dB)',
    type: 'text',
    default: '0',
    validation: 'integer',
    conditional: 'batchConfigure',
  },
  {
    key: 'cid',
    label: 'CID',
    type: 'checkbox',
    default: true,
    conditional: 'batchConfigure',
  },
  {
    key: 'echoCanceller',
    label: 'Echo Canceller',
    type: 'checkbox',
    default: true,
    conditional: 'batchConfigure',
  },
  {
    key: 'callWaiting',
    label: 'Call Waiting',
    type: 'checkbox',
    default: false,
    conditional: 'batchConfigure',
  },
  {
    key: 'dnd',
    label: 'DND (Do Not Disturb)',
    type: 'checkbox',
    default: false,
    conditional: 'batchConfigure',
  },
  {
    key: 'callForward',
    label: 'Call Forward',
    type: 'checkbox',
    default: false,
    conditional: 'batchConfigure',
  },
  {
    key: 'forwardType',
    label: 'Forward Type',
    type: 'select',
    options: ['Unconditional', 'Busy', 'No Reply'],
    default: 'Unconditional',
    conditional: 'batchConfigure',
    conditionalParent: 'callForward',
  },
  {
    key: 'forwardNumber',
    label: 'Forward Number',
    type: 'text',
    default: '',
    conditional: 'batchConfigure',
    conditionalParent: 'callForward',
  },
  {
    key: 'noAnswerDelayTime',
    label: 'Time for No Reply Forward (s)',
    type: 'text',
    default: '0',
    validation: 'integer',
    conditional: 'batchConfigure',
    conditionalParent: 'forwardType',
    conditionalParentValue: 'No Reply',
  },
  // Color ring removed per request
  {
    key: 'advancedConfiguration',
    label: 'Advanced Configuration',
    type: 'checkbox',
    default: false,
    conditional: 'batchConfigure',
  },
  {
    key: 'ringingParameter',
    label: 'Ringing Parameter',
    type: 'select',
    options: [
      'RING_ABS120V_CA',
      'RING_20HZ_SINE_DEF',
      'RING_ABS120V_AT',
      'RING_ABS120V_DEF',
      'RING_ABS120V_FI',
      'RING_ABS120V_FR',
      'RING_ABS120V_HK',
      'RING_ABS120V_JP',
      'RING_ABS120V_KR',
      'RING_ABS120V_SG',
      'RING_ABS120V_TW',
      'RING_ABS120V_US',
    ],
    default: 'RING_ABS120V_DEF',
    conditional: 'batchConfigure',
    conditionalParent: 'advancedConfiguration',
  },
  {
    key: 'feedVoltageParameter',
    label: 'Feed Voltage Parameter',
    type: 'select',
    options: [
      'DCFEED_48V_21MA_DEF',
      'DCFEED_48V_20MA_CN',
      'DCFEED_51V_23MA_ETSI',
      'DCFEED_50V_25MA_USA',
    ],
    default: 'DCFEED_48V_21MA_DEF',
    conditional: 'batchConfigure',
    conditionalParent: 'advancedConfiguration',
  },
  {
    key: 'impedanceParameter',
    label: 'Impedance Parameter',
    type: 'select',
    options: [
      'ZSYN_600_0_0_30_0',
      'ZSYN_270_750_150_30_0',
      'ZSYN_370_620_310_30_0',
      'ZSYN_220_820_120_30_0',
      'ZSYN_600_0_1000_30_0',
      'ZSYN_200_680_100_30_0',
      'ZSYN_220_820_115_30_0',
      'ZSYN_150_510_47_30_0',
      'ZSYN_270_910_120_30_0',
      'ZSYN_370_620_310_30_0',
      'ZSYN_900_0_0_30_0',
      'ZSYN_900_0_2160_30_0',
    ],
    default: 'ZSYN_200_680_100_30_0',
    conditional: 'batchConfigure',
    conditionalParent: 'advancedConfiguration',
  },
];

// Batch Modify Note
export const PORT_FXS_BATCH_MODIFY_NOTE = "Note: 'Auto Dial Number' goes into effect only if no dialing occurs during 'Wait Time before Auto Dial'.";

// Page Title
export const PORT_FXS_PAGE_TITLE = 'FXS Settings';

// Batch Modify Modal Title
export const PORT_FXS_BATCH_MODIFY_TITLE = 'FXS-Batch Modify';

