export const CALL_QUEUE_INITIAL_FORM = {
  queue_name: '',
  queue_number: '',
  pin: 'yes',
  agent_password: '',
  ring_strategy: 'ring_all',
  timeout_action: '',
  timeout_action_dest: '',
  caller_id_prefix: '',
  overflow_action: '',
  overflow_action_dest: '',
  agents_initial_status: 'logged_in',
  agent_call_timeout: 15,
  agent_announcement: '',
  agent_retry_time: 30,
  wrap_up_time: 30,
  max_no_answer: 0,
  discard_abandoned_after: 0,
  max_wait_time: 0,
  max_queue_length: 20,
  alert_info: '',
  music_on_hold: 'default',
  max_wait_no_agent: 90,
  queue_busy_resume: 'enable',
  transfer_prompt: '',
  agent_busy_announce: '',
  answer_announce: '',
  join_when_no_agent: false,
  join_announce: 'default',
  join_announce_playtime: 0,
  answer_type: 'answer',
  no_agent_announce: '',
  announce_position: true,
  announce_hold_time: true,
  call_duration: 60,
  announce_frequency: 30,
  periodic_sound: 'default',
  periodic_frequency: 0,
  busy_callback: 'no',
  busy_callback_key: '2',
  busy_callback_announce: 'default',
  selected_agents: [],
};

export const RING_STRATEGY_OPTIONS = [
  { value: 'ring_all', label: 'Ring All' },
  { value: 'longest_idle', label: 'Longest Idle Agent' },
  { value: 'round_robin', label: 'Round Robin' },
  { value: 'top_down', label: 'Top Down' },
  { value: 'least_talk_time', label: 'Agent With Least Talk Time' },
  { value: 'fewest_calls', label: 'Agent With Fewest Calls' },
  { value: 'random', label: 'Random' },
];

export const ACTION_OPTIONS = [
  { value: '', label: '' },
  { value: 'call_queue', label: 'Call Queue' },
  { value: 'callbacks', label: 'CallBacks' },
  { value: 'conference_rooms', label: 'Conference Rooms' },
  { value: 'disa', label: 'DISA' },
  { value: 'extensions', label: 'Extensions' },
  { value: 'faxtoemail', label: 'Fax to Mail' },
  { value: 'ivr_menus', label: 'IVR Menus' },
  { value: 'ring_groups', label: 'Ring Groups' },
  { value: 'voicemail', label: 'Voicemails' },
  { value: 'other', label: 'Other' },
];

export const ANNOUNCE_FREQ_OPTIONS = [0, 15, 20, 30, 45, 60, 90, 120, 150, 180, 240, 300];

export const CALL_QUEUE_TABLE_COLUMNS = [
  { key: 'check', label: 'Check' },
  { key: 'index', label: 'Index' },
  { key: 'queue_name', label: 'Queue Name' },
  { key: 'queue_number', label: 'Queue Number' },
  { key: 'ring_strategy', label: 'Ring Strategy' },
  { key: 'agents_count', label: 'Agents' },
  { key: 'modify', label: 'Modify' },
];
