export const SIP_SETTINGS_FIELDS = [
  { label: 'SIP Address of WAN', type: 'select', key: 'sipWan', options: [] },
  { label: 'SIP Signaling Port', type: 'text', key: 'sipPort', default: '5060', validation: 'integer' },
  { label: 'TLS', type: 'checkbox', key: 'tls',  },
  { label: 'SIP TLS Signaling Port', type: 'text', key: 'sipTlsPort', default: '5061', conditional: 'tls' },
  { label: 'SIP TLS Version', type: 'select', key: 'sipTlsVersion', options: ['SSLv23', 'TLS1.0', 'TLS1.1', 'TLS1.2'], default: 'SSLv23', conditional: 'tls' },
  { label: 'When the externally bound is enabled, only the externally bound address is matched to confirm the SIP trunk:', type: 'checkbox', key: 'externalBound' },
  { label: 'Send 180 before sending 183', type: 'radio', key: 'send180', options: ['Yes', 'No'], default: 'Yes'},
  { label: 'Send 183 Message', type: 'checkbox', key: 'send183'  },
  { label: 'Called Number Prefix for 180 Reply (Up to 5 are Allowed, Separated by ":")', type: 'text', key: 'calledPrefix', conditional: 'send183' },
  { label: 'Send 100rel', type: 'checkbox', key: 'send100rel' },
  { label: 'IP Call In First Route', type: 'select', key: 'ipCallRoute', options: ['IP to PSTN', 'IP to IP'] },
  { label: 'Soft-switch to be Connected', type: 'select', key: 'softSwitch', options: ['Others', 'VOS'] },
  { label: 'Send 183 Delay Time(ms)', type: 'text', key: 'send183DelayTime', conditional: 'softSwitch', conditionalValue: 'VOS' },
  { label: '183 Send Delay Mode', type: 'select', key: 'send183DelayMode', options: ['Mode 1', 'Mode 2'], default: 'Mode 1', conditional: 'softSwitch', conditionalValue: 'VOS' },
  { label: 'Hide CallerID', type: 'select', key: 'hideCallerId', options: ['Not Hidden', 'Hidden'] },
  { label: 'Obtain CallerID from', type: 'radio', key: 'obtainCallerId', options: ['Yes', 'No'], default: 'Yes' },
  { label: 'Obtain CalleeID from', type: 'select', key: 'obtainCalleeId', options: [" 'To' Field", "'Request' Field"] },
  { label: 'Send CalleeID from', type: 'select', key: 'sendCalleeId', options: ["'To' Field", "'Request' Field"] },
  { label: 'Asserted Identity Mode', type: 'select', key: 'assertedId', options: ['Disable', 'P-Asserted-Identity', 'P-Preferred-Identity'] },
  { label: 'Number in From Field not Manipulated', type: 'checkbox', key: 'numberInFromFieldNotManipulated', conditional: 'assertedId', conditionalValues: ['P-Asserted-Identity', 'P-Preferred-Identity'] },
  { label: 'Prack Send Mode', type: 'select', key: 'prackSend', options: ['Disable', 'Supported','Require'] },
  { label: 'DisplayName', type: 'select', key: 'displayName', options: ['Hide', 'Caller']},
  { label: 'UserName', type: 'select', key: 'userName', options: ['Change Caller', 'Caller'] },
  { label: 'Sip Address', type: 'select', key: 'sipAddress', options: ['IPv4', 'IPv6']},
  { label: 'Send/Obtain Redirecting Number/Original CalleeID from Diversion Field', type: 'radio', key: 'diversionField', options: ['Yes', 'No'], default: 'No'},
  { label: 'NAT Traversal', type: 'radio', key: 'natTraversal', options: ['Yes', 'No'], default: 'Yes' },
  { label: 'Traversal Type', type: 'select', key: 'traversalType', options: ['Port Mapping'], default: 'Port Mapping', conditional: 'natTraversal', conditionalValue: 'Yes' },
  { label: 'LAN1 Mapping Address', type: 'text', key: 'lan1MappingAddress', conditional: 'natTraversal', conditionalValue: 'Yes' },
  { label: 'LAN2 Mapping Address', type: 'text', key: 'lan2MappingAddress', conditional: 'natTraversal', conditionalValue: 'Yes' },
  { label: 'Set Redirection Parameter of REL Message When Receive Refer Message', type: 'checkbox', key: 'relMessage' },
  { label: 'RTP Self-adaption', type: 'radio', key: 'rtpSelf', options: ['Yes', 'No'], default: 'No' },
  { label: 'Rport', type: 'checkbox', key: 'rport' },
  { label: 'Filter Out Fake Calls (CallerID is the same as CalleeID)', type: 'checkbox', key: 'filterFake' },
  { label: 'Auto Reply of Source Address', type: 'checkbox', key: 'autoReply'},
  { label: 'Multiple Audio Selection', type: 'select', key: 'audioSelection', options: ['RTP/Audio', 'SRTP/Audio'] },
  { label: 'Send Response By Former Via', type: 'checkbox', key: 'responseVia'},
  { label: 'Registration related settings', type: 'checkbox', key: 'registrationSettings', default: false },
  { label: 'Time (min/month)', type: 'text', key: 'timeMinMonth', default: '5000', conditional: 'registrationSettings' },
  { label: 'SIP Registered Number Polling', type: 'select', key: 'sipRegisteredNumberPolling', options: ['Disable', 'Enable'], default: 'Disable', conditional: 'registrationSettings' },
  { label: 'Failed Count', type: 'text', key: 'failedCount', default: '0', conditional: 'sipRegisteredNumberPolling', conditionalValue: 'Enable' },
  { label: 'Recover Time Of Disable Account(m)', type: 'text', key: 'recoverTimeOfDisableAccount', default: '0', conditional: 'sipRegisteredNumberPolling', conditionalValue: 'Enable' },
  { label: 'Caller Prefix Grouping', type: 'select', key: 'callerPrefixGrouping', options: ['Disable', 'Enable'], default: 'Disable', conditional: 'sipRegisteredNumberPolling', conditionalValue: 'Enable' },
  { label: 'Caller Over Clocking(IP OUT)', type: 'checkbox', key: 'callerOverClock' },
  { label: 'Cycle(min)', type: 'text', key: 'cycleMin', default: '30', conditional: 'callerOverClock' },
  { label: 'Count Values', type: 'text', key: 'countValues', default: '30', conditional: 'callerOverClock' },
  { label: 'Interval(ms)', type: 'text', key: 'intervalMs', default: '0', conditional: 'callerOverClock' },
  { label: 'Eth Resource', type: 'checkbox', key: 'ethResource' },
  { label: 'SIP Account Numbers', type: 'text', key: 'sipAccountNumbers' },
  { label: 'SIP Account Registration Interval (MS)', type: 'text', key: 'sipAccountInterval' },
  { label: 'DSCP', type: 'text', key: 'dscp', default: '0', validation: 'integer' },
  { label: 'Calls from SIP Trunk Address only', type: 'checkbox', key: 'callsFromTrunkOnly' },
  { label: 'Match Call Count to SIP Trunk based on Source Address of INVITE', type: 'checkbox', key: 'matchCallCount' },
  { label: 'Switch Signal Port if SIP Registration Failed', type: 'checkbox', key: 'switchSignalPort' },
  { label: 'Hang up upon Call Time-out', type: 'checkbox', key: 'hangupTimeout'},
  { label: 'Maximum Call Overtime(min)', type: 'text', key: 'maximumCallOvertime', default: '1', conditional: 'hangupTimeout' },
  { label: 'Working Period', type: 'checkbox', key: 'workingPeriod', labelAfter: '24 Hours' },
  { label: 'Session Timer', type: 'checkbox', key: 'sessionTimer' },
  { label: 'Minimum Time (s)', type: 'text', key: 'minimumTime', default: '150', conditional: 'sessionTimer' },
  { label: 'Timeout (s)', type: 'text', key: 'timeout', default: '600', conditional: 'sessionTimer' },
  { label: 'Media Stream Processing', type: 'radio', key: 'mediaStream', options: ['Yes', 'No'], default: 'Yes'},
  { label: 'Sip Trunk Heart', type: 'checkbox', key: 'sipTrunkHeart'},
  { label: 'Trunk Heartbeat Cycle (s)', type: 'text', key: 'trunkHeartbeatCycle', default: '10', conditional: 'sipTrunkHeart' },
  { label: 'Allowed Times of NoResponse', type: 'text', key: 'allowedTimesOfNoResponse', default: '3', conditional: 'sipTrunkHeart' },
  { label: 'Early Media', type: 'checkbox', key: 'earlyMedia'},
  { label: 'Early Session', type: 'checkbox', key: 'earlySession' },
  { label: 'Support 100rel', type: 'radio', key: 'support100rel', options: ['Yes', 'No'], default: 'No' },
  { label: 'Not Wait ACK after Sending 200 OK', type: 'checkbox', key: 'notWaitAck'},
  { label: 'Match Sip Trunk Port', type: 'checkbox', key: 'matchTrunkPort' },
  { label: 'The Percentage of Registration Message Sending Cycle to Period of Validity(%)', type: 'text', key: 'regMsgPercent' },
  { label: 'Maximum Wait Answer Time(s)', type: 'text', key: 'maxWaitAnswer' },
  { label: 'Maximum Wait RTP Time(s)', type: 'text', key: 'maxWaitRtp' },
  { label: 'Maximum Wait PSTN Resource Time(ms)', type: 'text', key: 'maxWaitPstn' },
  { label: 'Switch Network Port by Packet Loss Rate', type: 'checkbox', key: 'switchNetPort' },
  { label: 'RTP Packet Loss Rate(%)', type: 'text', key: 'rtpPacketLossRate', default: '5', conditional: 'switchNetPort' },
  { label: 'Add Content to To Field in INVITE Message', type: 'radio', key: 'addContactTo', options: ['Yes', 'No'] },
  { label: 'Add Content(\'=\' replaced by \'+\')', type: 'text', key: 'addContent', conditional: 'addContactTo', conditionalValue: 'Yes' },
  { label: 'UserAgent Field', type: 'text', key: 'userAgent' },
];

export const SIP_SETTINGS_NOTE =
  'Note: Only one SIP Trunk can be configured and it is "Local Network Port" should be set to "Any Lan" once the feature "Switch Network Port by Packet Loss Rate" is enabled.';
