import React, { useState } from 'react';
import {
  CENTRALIZED_MANAGE_FIELDS,
  MANAGEMENT_PLATFORM_OPTIONS,
  CENTRALIZED_MANAGE_BUTTONS,
  CENTRALIZED_PROTOCOL_OPTIONS,
  SNMP_VERSION_OPTIONS,
} from '../constants/CentralizedManageConstants';
import { Button, Select, MenuItem, TextField, CircularProgress } from '@mui/material';
import { postLinuxCmd } from '../api/apiService';
import axiosInstance from '../api/axiosInstance';

const blueButtonSx = {
  background: 'linear-gradient(to bottom, #3bb6f5 0%, #0e8fd6 100%)',
  color: '#fff',
  fontWeight: 600,
  fontSize: 14,
  borderRadius: 1.5,
  minWidth: 120,
  boxShadow: '0 2px 6px #0002',
  textTransform: 'none',
  px: 3,
  py: 1.5,
  border: '1px solid #0e8fd6',
  '&:hover': {
    background: 'linear-gradient(to bottom, #0e8fd6 0%, #3bb6f5 100%)',
    color: '#fff',
  },
};

const initialForm = {
  centralizedManage: false,
  notificationSetting: false,
  trapServerPort: '162',
  cpuUsage: '90',
  memoryUsage: '90',
  highCps: '90',
  lowConnRate: '20',
  autoChangeGateway: false,
  managementPlatform: 'DCMS',
  centralizedProtocol: 'SNMP',
  snmpVersion: 'V2',
  snmpServerAddress: '127.0.0.1',
  monitoringPort: false,
  monitoringPortValue: '161',
  communityString: 'public',
  companyName: '',
  gatewayDesc: '',
  snmpServer: '127.0.0.1',
  authCode: '',
  workingStatus: 'Requesting authentication',
};

const CentralizedManage = () => {
  const [form, setForm] = useState(initialForm);
  const [isApplying, setIsApplying] = useState(false);
  const [applyStatus, setApplyStatus] = useState('');

  // Persisted state key
  const STORAGE_KEY = 'centralizedManageFormV1';

  // Restore saved form on mount
  React.useEffect(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (parsed && typeof parsed === 'object') {
          setForm({ ...initialForm, ...parsed });
        }
      }
    } catch {}
  }, []);


  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;

    setForm((prev) => {
      const newForm = {
        ...prev,
        [name]: type === 'checkbox' ? checked : value,
      };

      if (name === 'centralizedManage' && !checked) {
        newForm.notificationSetting = false;
      }

      if (name === 'notificationSetting' && !checked) {
        newForm.trapServerPort = '162';
        newForm.cpuUsage = '90';
        newForm.memoryUsage = '90';
        newForm.highCps = '90';
        newForm.lowConnRate = '20';
      }

      // Persist after every change
      try { localStorage.setItem(STORAGE_KEY, JSON.stringify(newForm)); } catch {}

      return newForm;
    });
  };

  const handleReset = () => {
    try { localStorage.removeItem(STORAGE_KEY); } catch {}
    setForm(initialForm);
  };

const buildSnmpCommand = () => {
    const version = (form.snmpVersion || 'V2').toUpperCase();
    if (version === 'V3') {
      return `echo 'SNMPv3 requires user credentials; configure via UI first'`;
    }

    const proto = version === 'V1' ? 'v1' : 'v2c';
    const community = form.communityString || 'public';
    const allow = (form.snmpServerAddress || '').trim();
    const listenPort = (form.monitoringPort && form.monitoringPortValue) ? String(form.monitoringPortValue) : '161';
    // Use snmpServerAddress (the field user enters) for trap destination
    const trapServer = (form.snmpServerAddress || '127.0.0.1').trim();

    const allowAllCheck = ['all', '*', '0.0.0.0/0'].includes(allow.toLowerCase());

    const safeCommunity = community.replace(/[^A-Za-z0-9_.-]/g, '');
    const safeTrapServer = trapServer.replace(/[^A-Za-z0-9_.:/-]/g, '');
    const safeAllow = allowAllCheck
      ? 'default'
      : (allow.replace(/[^A-Za-z0-9_.:/-]/g, '') || 'default');

    return `#!/bin/bash
CONF="/etc/snmp/snmpd.conf"
SCRIPT="/usr/local/bin/clixxo-device-info.sh"

echo "Starting SNMP configuration..."

# Create /etc/snmp directory if it doesn't exist
mkdir -p /etc/snmp 2>/dev/null || true

# Backup existing config
if [ -f "$CONF" ]; then
    cp "$CONF" "$CONF.bak.$(date +%s)" 2>/dev/null || true
fi

# Derive source selector
SRC="${safeAllow}"
if [ "$SRC" = "default" ] || [ -z "$SRC" ]; then
  SRC="default"
else
  if [ "$SRC" = "127.0.0.1" ] || [ "$SRC" = "::1" ]; then
    SRC="default"
  else
    DEVICE_IPS=$(ip -4 addr show 2>/dev/null | grep "inet " | awk '{print $2}' | cut -d/ -f1 || ifconfig 2>/dev/null | grep "inet " | awk '{print $2}' | cut -d: -f2 || echo "")
    if echo "$DEVICE_IPS" | grep -qFx "$SRC" 2>/dev/null; then
      SRC="default"
    fi
  fi
fi

# Write SNMP configuration
echo "Writing SNMP configuration..."
cat > "$CONF" <<CONFEOF
# Auto-generated by Centralized Manage
agentAddress udp:${listenPort}
master agentx
sysLocation CLIXXO
sysContact admin@clixxo

# Define view that includes ALL OIDs
view all included .1

# Security: com2sec maps community to security name
com2sec readonly $SRC ${safeCommunity}
com2sec readwrite $SRC private

# Group: maps security name to group
group MyROGroup ${proto} readonly
group MyRWGroup ${proto} readwrite

# Access: defines what the group can access
access MyROGroup "" any noauth exact all none none
access MyRWGroup "" any noauth exact all all all

# Also provide rocommunity for maximum compatibility
rocommunity ${safeCommunity} $SRC -V all
rwcommunity private $SRC -V all

# Remote management OIDs
pass .1.3.6.1.4.1.39871.3 /usr/local/bin/snmp_remote_management.sh

# Device Info OIDs from web_version.json
# .1.3.6.1.4.1.39871.1.1.2.0 = serial_no
# .1.3.6.1.4.1.39871.1.1.3.0 = web_version
# .1.3.6.1.4.1.39871.1.1.4.0 = service
# .1.3.6.1.4.1.39871.1.1.5.0 = uboot
# .1.3.6.1.4.1.39871.1.1.6.0 = kernel
# .1.3.6.1.4.1.39871.1.1.7.0 = firmware
# .1.3.6.1.4.1.39871.1.1.8.0 = SIP registration status
# .1.3.6.1.4.1.39871.1.1.9.0 = PRI/E1 status
pass_persist .1.3.6.1.4.1.39871 $SCRIPT
CONFEOF

echo "SNMP configuration written to $CONF"

# Update monitoring scripts with trap server and community
echo "Updating monitoring scripts..."
echo "Using TRAP_HOST: ${safeTrapServer}"
echo "Using COMMUNITY: ${safeCommunity}"

# Update clixxo-alarm-monitor.sh
if [ -f /usr/local/bin/clixxo-alarm-monitor.sh ]; then
    sed -i 's|^TRAP_HOST=.*|TRAP_HOST=\\"${safeTrapServer}\\"|' /usr/local/bin/clixxo-alarm-monitor.sh
    sed -i 's|^COMMUNITY=.*|COMMUNITY=\\"${safeCommunity}\\"|' /usr/local/bin/clixxo-alarm-monitor.sh
    echo "Updated clixxo-alarm-monitor.sh to TRAP_HOST=${safeTrapServer} COMMUNITY=${safeCommunity}"
    grep "^TRAP_HOST=" /usr/local/bin/clixxo-alarm-monitor.sh || echo "TRAP_HOST not found"
    grep "^COMMUNITY=" /usr/local/bin/clixxo-alarm-monitor.sh || echo "COMMUNITY not found"
fi

# Update snmp_remote_management.sh
if [ -f /usr/local/bin/snmp_remote_management.sh ]; then
    sed -i 's|^TRAP_HOST=.*|TRAP_HOST=\\"${safeTrapServer}\\"|' /usr/local/bin/snmp_remote_management.sh
    sed -i 's|^COMMUNITY=.*|COMMUNITY=\\"${safeCommunity}\\"|' /usr/local/bin/snmp_remote_management.sh
    echo "Updated snmp_remote_management.sh to TRAP_HOST=${safeTrapServer} COMMUNITY=${safeCommunity}"
    grep "^TRAP_HOST=" /usr/local/bin/snmp_remote_management.sh || echo "TRAP_HOST not found"
    grep "^COMMUNITY=" /usr/local/bin/snmp_remote_management.sh || echo "COMMUNITY not found"
fi

# Update clixxo-realtime-monitor.sh if exists
if [ -f /usr/local/bin/clixxo-realtime-monitor.sh ]; then
    sed -i 's|^TRAP_HOST=.*|TRAP_HOST=\\"${safeTrapServer}\\"|' /usr/local/bin/clixxo-realtime-monitor.sh
    sed -i 's|^COMMUNITY=.*|COMMUNITY=\\"${safeCommunity}\\"|' /usr/local/bin/clixxo-realtime-monitor.sh
    echo "Updated clixxo-realtime-monitor.sh to TRAP_HOST=${safeTrapServer} COMMUNITY=${safeCommunity}"
fi

# Restart SNMP service
echo "Restarting SNMP service..."
if systemctl restart snmpd 2>/dev/null; then
    echo "SNMP service restarted via systemctl"
elif service snmpd restart 2>/dev/null; then
    echo "SNMP service restarted via service command"
elif /etc/init.d/snmpd restart 2>/dev/null; then
    echo "SNMP service restarted via init.d"
else
    echo "Warning: Could not restart SNMP service"
fi

echo "Configuration complete!"
echo "SNMP listening on udp:${listenPort}"
echo "Community: ${safeCommunity}"
echo "Trap Server: ${safeTrapServer}"
echo "Custom OIDs: .1.3.6.1.4.1.39871.1.1.2.0 to .1.3.6.1.4.1.39871.1.1.9.0"
exit 0`;
  };

  const buildDcmsCommand = () => {
    const company = (form.companyName || '').replace(/[^A-Za-z0-9 _.-]/g, '');
    const desc = (form.gatewayDesc || '').replace(/[^A-Za-z0-9 _.-]/g, '');
    const snmpServer = (form.snmpServer || '').replace(/[^A-Za-z0-9_.:/-]/g, '');
    const auth = (form.authCode || '').replace(/[^A-Za-z0-9_.-]/g, '');

    return `set -e
CONF="/etc/clixxo/dcms.conf"
mkdir -p /etc/clixxo
cat > "$CONF" <<EOF
COMPANY_NAME="${company}"
GATEWAY_DESC="${desc}"
SNMP_SERVER="${snmpServer}"
AUTH_CODE="${auth}"
EOF
echo "DCMS configuration saved"`;
  };

  const validateIPAddress = (ip) => {
    // Allow 'all', '*', or '0.0.0.0/0' for wildcard access
    if (['all', '*', '0.0.0.0/0'].includes(ip.toLowerCase())) {
      return true;
    }
    
    // Validate IPv4 address format
    const ipv4Regex = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/;
    const match = ip.match(ipv4Regex);
    
    if (!match) {
      return false;
    }
    
    // Check each octet is between 0-255
    for (let i = 1; i <= 4; i++) {
      const octet = parseInt(match[i], 10);
      if (octet < 0 || octet > 255) {
        return false;
      }
    }
    
    return true;
  };

  const handleSave = async (e) => {
    e.preventDefault();

    try {
      setIsApplying(true);
      setApplyStatus('Connecting SNMP...');
      const commands = [];

      if (form.managementPlatform === 'DCMS') {
        if (!form.companyName || !form.gatewayDesc || !form.snmpServer || !form.authCode) {
          alert('Please fill Company Name, Gateway Description, SNMP Server Address and Authorization Code.');
          setIsApplying(false);
          return;
        }
        
        // Validate SNMP Server IP
        if (!validateIPAddress(form.snmpServer)) {
          alert('Please enter a valid IP address (e.g., 192.168.0.50) for SNMP Server. Partial IPs like "192" are not allowed.');
          setIsApplying(false);
          return;
        }
        
        commands.push(buildDcmsCommand());

        const snmpBackup = form.snmpServerAddress;
        const snmpAddr = form.snmpServer;
        form.snmpServerAddress = snmpAddr;
        commands.push(buildSnmpCommand());
        form.snmpServerAddress = snmpBackup;
      } else if (form.managementPlatform === 'Custom1' || form.managementPlatform === 'Others') {
        if (!form.snmpServerAddress) {
          alert('Please provide SNMP Server Address (client IP or "all").');
          setIsApplying(false);
          return;
        }
        
        // Validate SNMP Server IP
        if (!validateIPAddress(form.snmpServerAddress)) {
          alert('Please enter a valid IP address (e.g., 192.168.0.50). Partial IPs like "192" are not allowed.');
          setIsApplying(false);
          return;
        }
        
        commands.push(buildSnmpCommand());
      } else {
        alert('Unsupported Management Platform selection.');
        setIsApplying(false);
        return;
      }

      for (const cmd of commands) {
        // Use longer timeout for SNMP configuration (service restart can take time)
        let res;
        if (cmd.includes('snmpd')) {
          try {
            const response = await axiosInstance.post('/linuxcmd', { cmd }, { timeout: 60000 }); // 60 seconds for SNMP
            res = response.data;
          } catch (error) {
            console.error('SNMP command error:', error);
            throw new Error(error?.message || 'SNMP command failed');
          }
        } else {
          res = await postLinuxCmd({ cmd });
        }
        if (!(res && res.response)) {
          throw new Error(res?.message || 'Command failed');
        }
      }

      alert('Settings saved and commands executed successfully.');
      setApplyStatus('');
      // Persist current form so it remains after navigation
      try { localStorage.setItem(STORAGE_KEY, JSON.stringify(form)); } catch {}
    } catch (err) {
      console.error(err);
      alert(`Failed to apply settings: ${err.message || err}`);
      setApplyStatus('');
    }
    finally {
      setIsApplying(false);
    }
  };

  const handleDownloadMib = async () => {
    try {
      const cmd = `set -e
OUT="/tmp/vendor-mibs.mib"
rm -f "$OUT" 2>/dev/null || true

FOUND=0

# 1) Direct known vendor paths first (handles files without extensions)
for p in \
  /usr/share/snmp/mibs/ASTERISK-MIB \
  /usr/share/snmp/mibs/DIGIUM-MIB \
  /usr/share/snmp/mibs/CLIXXO-GW-MIB \
  /usr/share/snmp/mibs/RFC1213-MIB \
  /usr/share/snmp/mibs/CLIXXO-GENERATED-MIB\
  /usr/local/share/snmp/mibs/ASTERISK-MIB \
  /usr/local/share/snmp/mibs/DIGIUM-MIB \
  /usr/local/share/snmp/mibs/CLIXXO-GW-MIB \
  /usr/local/share/snmp/mibs/RFC1213-MIB \
  /usr/local/share/snmp/mibs/CLIXXO-GENERATED-MIB\
  /etc/snmp/mibs/ASTERISK-MIB \
  /etc/snmp/mibs/DIGIUM-MIB \
  /etc/snmp/mibs/CLIXXO-GW-MIB\
  /etc/snmp/mibs/RFC1213-MIB \
  /etc/snmp/mibs/CLIXXO-GENERATED-MIB\
do
  if [ -f "$p" ]; then
    echo "-- BEGIN $(basename \"$p\") --" >> "$OUT"; cat "$p" >> "$OUT"; echo "\n-- END $(basename \"$p\") --\n" >> "$OUT"; FOUND=1
  elif [ -d "$p" ]; then
    for f in "$p"/*; do [ -f "$f" ] && { echo "-- BEGIN $(basename \"$f\") --" >> "$OUT"; cat "$f" >> "$OUT"; echo "\n-- END $(basename \"$f\") --\n" >> "$OUT"; FOUND=1; }; done
  fi
done

# 2) If still not found, fallback to search (busybox-safe)
if [ $FOUND -eq 0 ]; then
  for d in /usr/share/snmp/mibs /usr/local/share/snmp/mibs /etc/snmp/mibs /var/lib/snmp/mibs /etc/clixxo/mibs /opt; do
    [ -d "$d" ] || continue
    for name in ASTERISK-MIB DIGIUM-MIB CLIXXO-GW-MIB RFC1213-MIB CLIXXO-GENERATED-MIB; do
      # try exact, then glob
      if [ -f "$d/$name" ]; then
        echo "-- BEGIN $name --" >> "$OUT"; cat "$d/$name" >> "$OUT"; echo "\n-- END $name --\n" >> "$OUT"; FOUND=1
      else
        for f in "$d"/${name}*; do
          [ -f "$f" ] || continue
          echo "-- BEGIN $(basename \"$f\") --" >> "$OUT"; cat "$f" >> "$OUT"; echo "\n-- END $(basename \"$f\") --\n" >> "$OUT"; FOUND=1
        done
      fi
    done
  done
fi

# 3) Generate and append CLIXXO Device Info MIB
cat >> "$OUT" <<'MIBEOF'

-- BEGIN CLIXXO-DEVICE-INFO-MIB --
CLIXXO-DEVICE-INFO-MIB DEFINITIONS ::= BEGIN

IMPORTS
    enterprises
        FROM RFC1155-SMI;

clixxoDeviceInfo OBJECT IDENTIFIER ::= { enterprises 39871 }

clixxoDeviceInfoTable OBJECT IDENTIFIER ::= { clixxoDeviceInfo 1 }

-- Device Information from web_version.json
clixxoSerialNumber OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS   read-only
    STATUS       current
    DESCRIPTION "Device serial number from web_version.json"
    ::= { clixxoDeviceInfoTable 1 }

clixxoWebVersion OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS   read-only
    STATUS       current
    DESCRIPTION "Web version from web_version.json"
    ::= { clixxoDeviceInfoTable 2 }

clixxoService OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS   read-only
    STATUS       current
    DESCRIPTION "Service version/timestamp from web_version.json"
    ::= { clixxoDeviceInfoTable 3 }

clixxoUboot OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS   read-only
    STATUS       current
    DESCRIPTION "Uboot version from web_version.json"
    ::= { clixxoDeviceInfoTable 4 }

clixxoKernel OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS   read-only
    STATUS       current
    DESCRIPTION "Kernel version from web_version.json"
    ::= { clixxoDeviceInfoTable 5 }

clixxoFirmware OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS   read-only
    STATUS       current
    DESCRIPTION "Firmware version from web_version.json"
    ::= { clixxoDeviceInfoTable 6 }

clixxoSipRegStatus OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS   read-only
    STATUS       current
    DESCRIPTION "SIP registration status (Registered/Unregistered/Rejected)"
    ::= { clixxoDeviceInfoTable 7 }

clixxoPriStatus OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS   read-only
    STATUS       current
    DESCRIPTION "PRI/E1 port status (pri show spans)"
    ::= { clixxoDeviceInfoTable 8 }

END
-- END CLIXXO-DEVICE-INFO-MIB --
MIBEOF
FOUND=1

if [ $FOUND -eq 1 ] && [ -s "$OUT" ]; then
  cat "$OUT"
else
  echo "ERROR=NOT_FOUND"
fi`;

      // Use longer timeout a bit for file read/concat but keep under 20s to avoid cancel
      const response = await axiosInstance.post('/linuxcmd', { cmd }, { timeout: 20000 });
      const out = String(response?.data?.responseData || '').trim();
      if (out.includes('ERROR=NOT_FOUND') || out.length === 0) {
        alert('No CLIXXO/ASTERISK/DIGIUM MIBs found. Ensure CLIXXO-GW-MIB, ASTERISK-MIB, DIGIUM-MIB, RFC1213-MIB or CLIXXO-GENERATED-MIB exist under /usr/share/snmp/mibs.');
        return;
      }

      const blob = new Blob([out], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'vendor-mibs.mib';
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error(err);
      const fallback = '# Failed to retrieve MIB file. Please try again.';
      const blob = new Blob([fallback], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'vendor-mibs.mib';
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    }
  };

  return (
    <div className="bg-gray-50 min-h-[calc(100vh-150px)] py-0 flex flex-col items-center" style={{ backgroundColor: '#dde0e4' }}>
      <div className="w-full max-w-4xl mx-auto">
        <div className="w-full h-8 bg-gradient-to-b from-[#b3e0ff] via-[#6ec1f7] to-[#3b8fd6] flex items-center justify-center font-semibold text-xl text-gray-700 shadow mb-0">
          Centralized Manage
        </div>

        <div className="border-2 border-gray-400 border-t-0 shadow-sm flex flex-col" style={{ backgroundColor: '#dde0e4' }}>
          <div className="w-full max-w-3xl mx-auto">
            <form onSubmit={handleSave} className="w-full grid grid-cols-1 md:grid-cols-2 gap-x-4 md:gap-x-8 gap-y-4 px-2 md:px-8 py-6">
              {CENTRALIZED_MANAGE_FIELDS.map((field) => {
                if (field.name === 'monitoringPortValue') return null;
                if (field.name === 'workingStatus') return null;
                if (
                  !form.notificationSetting &&
                  ['trapServerPort', 'cpuUsage', 'memoryUsage', 'highCps', 'lowConnRate'].includes(field.name)
                )
                  return null;
                if (field.conditional && form.managementPlatform === 'DCMS') return null;
                if (field.dcmsOnly && form.managementPlatform !== 'DCMS') return null;

                const isEditable = form.centralizedManage || field.name === 'authCode';

                return (
                  <React.Fragment key={field.name}>
                    <div className="flex items-center text-gray-800 text-left pl-4 whitespace-nowrap min-h-[36px]" style={{ fontSize: '14px' }}>
                      {field.label}
                    </div>
                    <div className="flex items-center min-h-[36px]">
                      {field.name === 'monitoringPort' ? (
                        <div className="flex items-center w-full">
                          <input
                            type="checkbox"
                            checked={!!form.monitoringPort}
                            onChange={handleChange}
                            name="monitoringPort"
                            disabled={!isEditable}
                            className="w-4 h-4 accent-blue-600"
                          />
                          <TextField
                            variant="outlined"
                            size="small"
                            type="text"
                            name="monitoringPortValue"
                            value={form.monitoringPortValue || '161'}
                            onChange={handleChange}
                            className="bg-white flex-1 ml-2"
                            disabled={!isEditable || !form.monitoringPort}
                          />
                        </div>
                      ) : field.type === 'checkbox' ? (
                        <div className="flex items-center">
                          <input
                            type="checkbox"
                            checked={!!form[field.name]}
                            onChange={handleChange}
                            name={field.name}
                            disabled={!form.centralizedManage && field.name !== 'centralizedManage'}
                            className="w-4 h-4 accent-blue-600"
                          />
                          <span className="ml-1 text-gray-700" style={{ fontSize: '14px' }}>
                            Enable
                          </span>
                        </div>
                      ) : field.type === 'select' ? (
                        <Select
                          value={form[field.name]}
                          onChange={handleChange}
                          name={field.name}
                          size="small"
                          variant="outlined"
                          className="w-full"
                          disabled={!isEditable}
                        >
                          {(field.name === 'centralizedProtocol'
                            ? CENTRALIZED_PROTOCOL_OPTIONS
                            : field.name === 'snmpVersion'
                            ? SNMP_VERSION_OPTIONS
                            : MANAGEMENT_PLATFORM_OPTIONS
                          ).map((opt) => (
                            <MenuItem key={opt.value} value={opt.value}>
                              {opt.label}
                            </MenuItem>
                          ))}
                        </Select>
                      ) : (
                        <TextField
                          variant="outlined"
                          size="small"
                          type="text"
                          name={field.name}
                          value={form[field.name] || ''}
                          onChange={handleChange}
                          disabled={!isEditable}
                        />
                      )}
                    </div>
                  </React.Fragment>
                );
              })}
            </form>
          </div>
        </div>

        <div className="flex flex-col sm:flex-row justify-center gap-8 mt-8 w-full max-w-3xl mx-auto">
          <Button variant="contained" sx={blueButtonSx} onClick={handleSave} disabled={isApplying}>
            {isApplying ? 'Connecting…' : 'Save'}
          </Button>
          <Button variant="contained" sx={blueButtonSx} onClick={handleReset}>
            Reset
          </Button>
          <Button variant="contained" sx={blueButtonSx} onClick={handleDownloadMib}>
            {CENTRALIZED_MANAGE_BUTTONS[2].label}
          </Button>
        </div>
        {isApplying && (
          <div className="flex justify-center items-center gap-3 mt-4 text-gray-700">
            <CircularProgress size={18} />
            <span style={{ fontSize: 14 }}>{applyStatus || 'Applying…'}</span>
          </div>
        )}
      </div>
    </div>
  );
};

export default CentralizedManage;
