export const SIP_COMPATIBILITY_FIELDS = [
  { label: 'Obtain CalleeID from', type: 'select', key: 'obtainCalleeId', options: ["'Username' Field", "'Request' Field", "'Display Name' Field"], default: "'Request' Field" },
  { label: 'Set CallerID position', type: 'select', key: 'callerIdPosition', options: ['Username of From Field', 'Display Name of From Field'], default: 'Username of From Field' },
  { label: 'Obtain CallerID from', type: 'select', key: 'obtainCallerId', options: ['Username of From Field', 'Display Name of From Field'], default: 'Username of From Field' },
  { label: 'Use Source Address', type: 'checkbox', key: 'useSourceAddress', default: false },
  { label: 'Use Contact Address', type: 'checkbox', key: 'useContactAddress', default: false },
  { label: 'Call Transfer Mode', type: 'select', key: 'callTransferMode', options: ['Internal Handling', 'Platform to Handle SIP Info'], default: 'Platform to Handle SIP Info' },
  { label: 'Internal Handle', type: 'select', key: 'internalHandle', options: ['Match Port Number', 'Search Idle FXO Channel'], default: 'Match Port Number', conditional: 'callTransferMode', conditionalValue: 'Internal Handling' },
  { label: 'Call Flash Mode', type: 'select', key: 'callFlashMode', options: ['Internal Handling', 'Platform to handle Sip Info'], default: 'Platform to handle Sip Info' },
  { label: 'Hold Music Source', type: 'select', key: 'holdMusicSource', options: ['Remote', 'Local'], default: 'Remote', conditional: 'callFlashMode', conditionalValue: 'Platform to handle Sip Info' },
  { label: 'Two Stage Dialing for SIP Incoming Call', type: 'checkbox', key: 'twoStageDialing', default: false },
  { label: 'Maximum Wait Answer Time (s)', type: 'text', key: 'maxWaitAnswer', default: '60', validation: 'integer' },
  { label: 'Set SIP Identifying', type: 'text', key: 'sipIdentifying', default: 'Gateway' },
  { label: 'Maximum Wait RTP Time (s)', type: 'text', key: 'maxWaitRtp', default: '0', validation: 'integer' },
  { label: 'Call Abnormal Hangup Detection', type: 'checkbox', key: 'abnormalHangup', default: false },
  { label: 'Cycle(s)', type: 'text', key: 'abnormalHangupCycle', default: '0', validation: 'integer', conditional: 'abnormalHangup' },
  { label: 'Server Status Detection', type: 'checkbox', key: 'serverStatusDetection', default: false },
  { label: 'Cycle(s)', type: 'text', key: 'cycle', default: '10', validation: 'integer', conditional: 'serverStatusDetection' },
  { label: 'Send Cue Tone', type: 'checkbox', key: 'sendCueTone', default: false, conditional: 'serverStatusDetection' },
  { label: 'SIP Encryption', type: 'checkbox', key: 'sipEncryption', default: false },
  { label: 'Encryption Criterion', type: 'select', key: 'encryptionCriterion', options: ['VOS1.1', 'VOS2.0'], default: 'VOS1.1', conditional: 'sipEncryption' },
  { label: 'Identifier', type: 'text', key: 'identifier', default: '', conditional: 'encryptionCriterion', conditionalValue: 'VOS1.1' },
  { label: 'Key', type: 'text', key: 'key', default: '', conditional: 'sipEncryption' },
  { label: 'RTP Encryption', type: 'checkbox', key: 'rtpEncryption', default: false },
  { label: 'INVITE 100rel', type: 'checkbox', key: 'invite100rel', default: false },
  { label: 'Ignore ACK', type: 'checkbox', key: 'ignoreAck', default: false },
  { label: 'User-defined SIP Code', type: 'checkbox', key: 'userDefinedSipCode', default: false },
  { label: 'No Idle Port in Port Group', type: 'text', key: 'noIdlePort', default: '503', validation: 'integer', conditional: 'userDefinedSipCode' },
  { label: 'Called Party Disconnected (Talking, Power off, Rejected, No Response, Not in Service)', type: 'text', key: 'calledPartyDisconnected', default: '486', validation: 'integer', conditional: 'userDefinedSipCode' },
  { label: 'Route Failed', type: 'text', key: 'routeFailed', default: '488', validation: 'integer', conditional: 'userDefinedSipCode' },
  { label: 'Use Iptables', type: 'checkbox', key: 'useIptables', default: true },
  { label: 'Manage Refer', type: 'select', key: 'manageRefer', options: ['Default', 'FXO Blind call transfer'], default: 'Default' },
  { label: 'FXO HangUp Time', type: 'text', key: 'fxoHangupTime', default: '7', validation: 'integer', conditional: 'manageRefer', conditionalValue: 'FXO Blind call transfer' },
];

