export const RECORD_SETTINGS_CARD_RADIUS = 4;

export const RECORD_SETTINGS_LAPTOP_NARROW_MQ = "(max-width: 1366px)";

export const RECORD_SETTINGS_MAIN_SECTION_HEADING_LEFT = -20;

export const RECORD_SETTINGS_SECTION_HEADING_COLOR = "#30415A";
